package Euler;


/*  
  * Solution to Project Euler problem 2 
  * by KW
  *  
  * Fibonacci numbers
  * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  * 1+2=3
  * 2+3=5
  * 3+5=8
  *
  */   

public class p002 { 
 	 
 	public static void main(String[] args) { 
                System.out.println("This shows the first 10 values of the Fibonacci sequence:");

 		int sum = 0; 
                int A = 1, B = 0, X = 2; 

 		for (int i = 0; i < 10; i++) { 
 			B = A;
                        A = X;
                        X = (A+B);
 			sum = (sum+X); 
                        System.out.println(+A+ " + " +B+ " = " +X);
 		} 
        }

}
